### ISSUE TITLE
The code is swapping EL as GR for Greece

### ISSUE THREAD

**Issue by alex-andrey** [agilegeeks/pyVies#7]
Hello,

Thank you for writing/maintaining this package. 
I am having trouble with Greek VAT numbers, for example :

```
from pyVies import api

vies = api.Vies()
print(vies.clean('EL123456789'))
```

should work but returns 

```
---------------------------------------------------------------------------
ViesValidationError                       Traceback (most recent call last)
<ipython-input-44-80fb3303feb4> in <module>
      2 
      3 vies = api.Vies()
----> 4 print(vies.clean('EL123456789'))

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyVies/api.py in clean(self, vat_number, vat_country_code)
     99 
    100         if vat_country_code not in VAT_NUMBER_REGEXPS.keys():
--> 101             raise ViesValidationError('Invalid VAT country')
    102 
    103         if len(vat_number)>2:

ViesValidationError: Invalid VAT country
```

I believe this is because of this line in the code:
https://github.com/agilegeeks/pyVies/blob/7ac9dce59ffae880fd93d5766334643b809a068b/pyVies/api.py#L96

`EL` should not be swapped for `GR`, it should stay as `EL`. However, if someone put `GR` then we should swap it for `EL`

So the code should be:
```
            if vat_country_code== 'GR':
                vat_country_code = 'EL'
```

**Comment by erfannariman** [comment]
This makes sense yes and looks like a bug, source checked: [link](https://en.wikipedia.org/wiki/VAT_identification_number). I submitted a PR to fix this.

Thanks for opening the issue
